"""
Prompt Bazaar V7 — ML Training Corpus
Curated semantic descriptions for TF-IDF + cosine similarity classifiers.
Each category contains multiple representative sentences that capture
the semantic space of that class.
"""

# =============================================================================
# INTENT CORPUS — 16 intent categories, 10+ examples each
# =============================================================================
INTENT_CORPUS = {
    "Create": [
        "create a new application from scratch",
        "build something completely new",
        "make a fresh project with modern features",
        "develop a brand new system",
        "construct a new platform for users",
        "set up a new website with full functionality",
        "initialize a new codebase and project structure",
        "start building a new product from the ground up",
        "craft a new solution for this business problem",
        "design and implement a new tool"
    ],
    "Generate": [
        "generate content automatically",
        "produce output based on input parameters",
        "create generated text for marketing",
        "auto-generate reports and summaries",
        "generate images using AI models",
        "produce code snippets from descriptions",
        "generate documentation for the API",
        "write generated blog posts and articles",
        "produce visual assets with AI tools",
        "generate a dataset for training"
    ],
    "Analyze": [
        "analyze data trends and patterns",
        "perform deep analysis of user behavior",
        "examine the performance metrics",
        "analyze code quality and technical debt",
        "conduct market analysis and competitive research",
        "evaluate the effectiveness of the campaign",
        "review and assess the current system architecture",
        "investigate root cause of production issues",
        "study the data distribution and anomalies",
        "audit the security posture of the application"
    ],
    "Explain": [
        "explain how this algorithm works step by step",
        "describe the architecture in simple terms",
        "clarify the differences between these approaches",
        "teach me the fundamentals of this concept",
        "break down this complex topic into simple parts",
        "illustrate how the system processes requests",
        "explain the trade-offs between these technologies",
        "walk through the implementation details",
        "describe what this code does line by line",
        "help me understand this scientific concept"
    ],
    "Build": [
        "build a full-stack web application",
        "construct a microservices architecture",
        "build a mobile app with React Native",
        "implement a CI/CD pipeline",
        "build a data processing pipeline",
        "construct a REST API with authentication",
        "build a real-time dashboard",
        "implement a machine learning pipeline",
        "build a scalable cloud infrastructure",
        "construct an e-commerce platform"
    ],
    "Compare": [
        "compare these two frameworks and their features",
        "evaluate the pros and cons of each approach",
        "contrast the performance of different databases",
        "compare pricing models of cloud providers",
        "benchmark these algorithms against each other",
        "weigh the advantages of monolith vs microservices",
        "compare React vs Vue for this use case",
        "contrast supervised and unsupervised learning methods",
        "evaluate which technology stack is more suitable",
        "compare the security features of these platforms"
    ],
    "Optimize": [
        "optimize the database query performance",
        "improve page load speed and core web vitals",
        "reduce memory usage and resource consumption",
        "optimize the machine learning model accuracy",
        "improve the user experience and conversion rate",
        "enhance the search engine ranking and SEO",
        "optimize the API response time and throughput",
        "refactor the code for better maintainability",
        "tune hyperparameters for better model performance",
        "streamline the deployment process"
    ],
    "Rewrite": [
        "rewrite this code in a cleaner way",
        "refactor the legacy codebase to modern standards",
        "rewrite the content for a different audience",
        "convert this synchronous code to async",
        "rewrite the SQL queries for better performance",
        "transform this monolith into microservices",
        "rewrite the documentation with better examples",
        "modernize the outdated frontend framework",
        "rewrite this prompt to be more specific",
        "convert this script from Python 2 to Python 3"
    ],
    "Summarize": [
        "summarize this lengthy article into key points",
        "create an executive summary of the report",
        "condense this research paper into highlights",
        "provide a brief overview of the findings",
        "summarize the meeting notes and action items",
        "distill the key insights from this dataset",
        "create a summary for the stakeholder presentation",
        "summarize the changes in the latest release",
        "provide a concise overview of the project status",
        "extract the main takeaways from this document"
    ],
    "Debug": [
        "debug the error in the production system",
        "fix the bug causing the application crash",
        "troubleshoot the connection timeout issue",
        "resolve the memory leak in the backend",
        "debug the failing unit tests",
        "fix the broken authentication flow",
        "diagnose the performance bottleneck",
        "troubleshoot the deployment failure",
        "resolve the race condition in concurrent processing",
        "debug the data inconsistency issue"
    ],
    "Translate": [
        "translate this content to multiple languages",
        "convert the API documentation to Spanish",
        "localize the application for international markets",
        "translate the user interface to Hindi",
        "adapt the marketing content for Telugu audience",
        "translate technical documentation to plain language",
        "convert this code from Java to Python",
        "translate the legal terms into simple English",
        "port this algorithm to a different programming language",
        "localize the error messages for regional users"
    ],
    "Research": [
        "research the latest trends in AI technology",
        "investigate best practices for cloud security",
        "study the market landscape for competitor analysis",
        "explore emerging technologies in healthcare",
        "research user preferences and behavior patterns",
        "investigate the feasibility of this approach",
        "conduct a literature review on this topic",
        "research regulatory requirements for compliance",
        "explore alternative solutions and approaches",
        "study the impact of this technology on industry"
    ],
    "Design": [
        "design the user interface for the mobile app",
        "create a wireframe for the landing page",
        "design the database schema and relationships",
        "create a system architecture diagram",
        "design the user experience flow",
        "create a design system with components",
        "design the API contract and endpoints",
        "create mockups for the admin dashboard",
        "design the information architecture",
        "create a visual identity and brand guidelines"
    ],
    "Teach": [
        "teach me how to use this framework",
        "create a tutorial for beginners",
        "write a learning guide for advanced concepts",
        "develop a curriculum for this course",
        "create educational content for students",
        "build a step-by-step learning path",
        "teach the fundamentals with practical examples",
        "create interactive learning exercises",
        "develop training materials for the team",
        "write a comprehensive beginner's guide"
    ],
    "Plan": [
        "plan the project roadmap and milestones",
        "create a strategic plan for product launch",
        "design the sprint planning and backlog",
        "plan the migration strategy for the database",
        "create an implementation timeline",
        "plan the testing strategy and test cases",
        "design the deployment and rollout plan",
        "create a business continuity plan",
        "plan the budget and resource allocation",
        "design the go-to-market strategy"
    ],
    "Automate": [
        "automate the repetitive deployment tasks",
        "create automated testing pipelines",
        "build workflow automation with triggers",
        "automate data collection and processing",
        "set up automated monitoring and alerts",
        "create automated email sequences",
        "build a CI/CD automation pipeline",
        "automate report generation and distribution",
        "create automated backup and recovery",
        "build robotic process automation workflows"
    ]
}

# =============================================================================
# DOMAIN CORPUS — 26 domains, 15+ semantic descriptions each
# =============================================================================
DOMAIN_CORPUS = {
    "Restaurant": [
        "restaurant website with online menu and table booking",
        "food ordering platform for a cafe or bistro",
        "dining establishment with reservation management",
        "restaurant brand identity and menu design",
        "food delivery integration and kitchen management",
        "hospitality business with chef profiles and cuisine showcase",
        "bakery website with online ordering and pickup",
        "bar and pub website with drink menu and events",
        "catering service platform with packages and booking",
        "food truck business with location tracking",
        "fine dining experience with wine pairing and tasting menu",
        "fast food chain management and franchise operations",
        "restaurant loyalty program and customer engagement",
        "food photography and menu styling guidelines",
        "restaurant supply chain and inventory management"
    ],
    "Programming": [
        "software development and coding project",
        "build a web application with modern frameworks",
        "API development with RESTful endpoints",
        "backend service with database integration",
        "frontend development with React or Vue",
        "full-stack application with authentication",
        "mobile app development with cross-platform framework",
        "microservices architecture with Docker containers",
        "code refactoring and technical debt cleanup",
        "debugging and fixing software bugs",
        "implement algorithms and data structures",
        "build a command line tool or CLI utility",
        "develop a browser extension or plugin",
        "create a library or SDK for developers",
        "build a real-time application with WebSocket"
    ],
    "Marketing": [
        "marketing campaign strategy and execution plan",
        "digital marketing with SEO and SEM optimization",
        "social media marketing and content strategy",
        "email marketing automation and drip campaigns",
        "brand positioning and competitive analysis",
        "growth marketing and user acquisition strategy",
        "content marketing with blog and article planning",
        "paid advertising campaign on Google and Facebook",
        "influencer marketing and partnership strategy",
        "conversion rate optimization and funnel design",
        "market research and consumer behavior analysis",
        "product launch marketing plan",
        "affiliate marketing program setup",
        "marketing analytics and ROI measurement",
        "viral marketing and community building"
    ],
    "Business": [
        "business strategy and operational planning",
        "startup business model and pitch deck",
        "business process optimization and automation",
        "project management and team coordination",
        "product management and feature prioritization",
        "business intelligence and reporting dashboard",
        "organizational management and leadership",
        "venture capital fundraising and investor relations",
        "supply chain management and logistics",
        "customer relationship management strategy",
        "e-commerce business operations and growth",
        "secure e-commerce website with shopping cart",
        "online store selling physical products like shoes or apparel",
        "retail business and online shopping platform",
        "b2b and b2c digital storefront and checkout",
        "digital products marketplace and inventory",
        "franchise development and expansion planning",
        "mergers and acquisitions due diligence",
        "corporate governance and risk management",
        "business continuity and disaster recovery planning"
    ],
    "Healthcare": [
        "healthcare application with patient portal",
        "medical records management system",
        "telemedicine platform for remote consultations",
        "hospital management and clinical workflows",
        "health monitoring app with vital signs tracking",
        "HIPAA compliant data processing and storage",
        "electronic health records EHR integration",
        "pharmaceutical inventory and drug management",
        "medical imaging and diagnostic AI system",
        "mental health and wellness application",
        "clinical trial management and research platform",
        "healthcare insurance claims processing",
        "nursing care coordination system",
        "patient scheduling and appointment management",
        "healthcare analytics and outcome prediction"
    ],
    "Legal": [
        "legal document management and automation",
        "contract review and compliance checking",
        "law firm management and case tracking",
        "GDPR and data privacy compliance",
        "intellectual property management system",
        "litigation support and legal research",
        "regulatory compliance and audit preparation",
        "legal billing and time tracking system",
        "court filing and document submission",
        "employment law compliance and HR legal",
        "legal technology and AI-assisted analysis",
        "notary and certification management",
        "legal knowledge base and precedent search",
        "compliance monitoring and reporting",
        "corporate legal department operations"
    ],
    "Finance": [
        "financial technology and banking application",
        "investment portfolio management and tracking",
        "payment processing and transaction system",
        "cryptocurrency and blockchain platform",
        "financial reporting and accounting software",
        "insurance policy management and claims",
        "trading platform with real-time market data",
        "personal finance and budgeting application",
        "credit scoring and risk assessment model",
        "regulatory compliance for financial services",
        "wealth management and advisory platform",
        "PCI-DSS compliant payment gateway",
        "fraud detection and anti-money laundering",
        "financial forecasting and predictive analytics",
        "tax preparation and filing system"
    ],
    "Education": [
        "learning management system for online courses",
        "educational platform with student tracking",
        "e-learning content delivery and assessment",
        "school management and administration system",
        "tutoring platform with video conferencing",
        "gamified learning experience for students",
        "curriculum development and lesson planning",
        "student performance analytics and reporting",
        "university admission and enrollment system",
        "certification and credential management",
        "educational content creation and publishing",
        "virtual classroom with interactive tools",
        "adaptive learning with personalized paths",
        "academic research collaboration platform",
        "training and professional development system"
    ],
    "Cloud": [
        "cloud infrastructure design and deployment",
        "AWS Azure GCP cloud architecture",
        "serverless computing and functions",
        "container orchestration with Kubernetes",
        "cloud migration strategy and execution",
        "infrastructure as code with Terraform",
        "cloud security and IAM management",
        "multi-cloud and hybrid cloud architecture",
        "cloud cost optimization and governance",
        "auto-scaling and load balancing",
        "cloud monitoring and observability",
        "DevOps pipeline and deployment automation",
        "cloud-native application development",
        "disaster recovery and business continuity",
        "cloud database management and optimization"
    ],
    "Cybersecurity": [
        "cybersecurity assessment and penetration testing",
        "network security and firewall configuration",
        "security operations center and threat monitoring",
        "vulnerability assessment and remediation",
        "security architecture and zero trust implementation",
        "incident response planning and execution",
        "encryption and data protection strategies",
        "identity and access management IAM",
        "security compliance and audit reporting",
        "threat intelligence and risk analysis",
        "web application security and OWASP compliance",
        "cloud security posture management",
        "security awareness training program",
        "malware analysis and reverse engineering",
        "security information and event management SIEM"
    ],
    "DataScience": [
        "data analysis and statistical modeling",
        "data pipeline and ETL processing",
        "business intelligence and analytics dashboard",
        "exploratory data analysis and visualization",
        "predictive modeling and forecasting",
        "data warehouse and lake architecture",
        "big data processing with Spark or Hadoop",
        "data quality management and cleansing",
        "time series analysis and trend detection",
        "A/B testing and experimental design",
        "natural language processing and text analytics",
        "recommendation system and collaborative filtering",
        "customer segmentation and clustering",
        "data governance and metadata management",
        "geospatial data analysis and mapping"
    ],
    "MachineLearning": [
        "machine learning model training and deployment",
        "deep learning neural network architecture",
        "natural language processing with transformers",
        "computer vision and image recognition",
        "reinforcement learning and agent training",
        "model evaluation and hyperparameter tuning",
        "MLOps and model lifecycle management",
        "transfer learning and fine-tuning pretrained models",
        "generative AI and large language models",
        "feature engineering and selection",
        "model interpretability and explainability",
        "federated learning and privacy-preserving ML",
        "AutoML and neural architecture search",
        "anomaly detection and outlier analysis",
        "time series forecasting with neural networks"
    ],
    "PromptEngineering": [
        "prompt engineering and LLM optimization",
        "system prompt design for AI assistants",
        "few-shot and zero-shot prompting techniques",
        "chain-of-thought reasoning prompts",
        "prompt template design for specific tasks",
        "LLM output formatting and structured generation",
        "negative prompting to prevent hallucinations",
        "role-based persona prompts for AI models",
        "retrieval augmented generation RAG system",
        "prompt evaluation and quality scoring",
        "multi-turn conversation design",
        "tool-use and function calling prompts",
        "prompt injection prevention and security",
        "AI agent instruction design",
        "custom GPT and chatbot creation"
    ],
    "AIAgents": [
        "AI agent architecture and orchestration",
        "multi-agent system with task delegation",
        "autonomous agent with tool integration",
        "LangChain or CrewAI agent framework",
        "agent workflow with decision making",
        "tool calling and API integration for agents",
        "agent memory management and context window",
        "agentic RAG with knowledge retrieval",
        "n8n workflow automation with AI agents",
        "autonomous coding agent development",
        "agent evaluation and benchmarking",
        "agent safety and guardrails",
        "hierarchical multi-agent teams",
        "agent planning and reasoning systems",
        "agent observability and debugging"
    ],
    "UIUX": [
        "user interface design and visual layout",
        "user experience research and testing",
        "wireframing and prototyping with Figma",
        "design system and component library",
        "interaction design and micro-animations",
        "accessibility compliance and WCAG standards",
        "responsive design for mobile and desktop",
        "information architecture and navigation",
        "usability testing and heuristic evaluation",
        "user persona development and journey mapping",
        "color theory and typography selection",
        "design tokens and theme customization",
        "dark mode and light mode design",
        "icon design and illustration style",
        "design handoff and developer collaboration"
    ],
    "ImageGeneration": [
        "AI image generation with Midjourney or DALL-E",
        "visual art creation with Stable Diffusion",
        "photorealistic rendering and digital artwork",
        "character design and concept art generation",
        "product photography and mockup creation",
        "landscape and environment art generation",
        "portrait and headshot AI generation",
        "logo design and brand visual assets",
        "texture and pattern generation for design",
        "image editing and style transfer",
        "architectural visualization and rendering",
        "fashion design and clothing visualization",
        "game asset and sprite generation",
        "illustration and book cover design",
        "photo manipulation and composite creation"
    ],
    "VideoGeneration": [
        "AI video generation with Runway or Sora",
        "video content creation and editing",
        "animation and motion graphics production",
        "promotional video and commercial creation",
        "educational video content production",
        "social media video and reels creation",
        "product demo and explainer video",
        "cinematic footage and film production",
        "video transition and effects design",
        "music video and visual storytelling",
        "video scriptwriting and storyboarding",
        "live streaming and broadcast production",
        "virtual production and green screen",
        "documentary and interview production",
        "video thumbnail and cover design"
    ],
    "Writing": [
        "content writing and copywriting",
        "blog post and article creation",
        "technical writing and documentation",
        "creative writing and storytelling",
        "newsletter and email content writing",
        "press release and media communication",
        "white paper and research writing",
        "social media caption and post writing",
        "book writing and manuscript editing",
        "speechwriting and presentation content",
        "product description and catalog writing",
        "grant writing and proposal creation",
        "scriptwriting for video and podcast",
        "website copy and landing page content",
        "academic writing and thesis composition"
    ],
    "Research": [
        "academic research and literature review",
        "market research and industry analysis",
        "user research and surveys",
        "competitive analysis and benchmarking",
        "scientific research and experimental design",
        "data-driven research and hypothesis testing",
        "policy research and impact assessment",
        "technology research and trend analysis",
        "ethnographic research and qualitative studies",
        "research methodology and framework design",
        "systematic review and meta-analysis",
        "case study research and documentation",
        "clinical research and trial design",
        "UX research and usability studies",
        "research paper writing and publication"
    ],
    "Resume": [
        "resume writing and CV creation",
        "cover letter and job application",
        "LinkedIn profile optimization",
        "career development and job search strategy",
        "portfolio website for professionals",
        "interview preparation and practice",
        "ATS-friendly resume formatting",
        "executive resume and personal branding",
        "career transition and skill mapping",
        "reference letter and recommendation writing",
        "professional bio and about page",
        "salary negotiation and offer evaluation",
        "networking strategy and outreach",
        "internship application and resume",
        "academic CV for faculty positions"
    ],
    "SocialMedia": [
        "social media strategy and content planning",
        "Instagram content creation and scheduling",
        "TikTok video strategy and viral content",
        "LinkedIn thought leadership and networking",
        "Twitter engagement and community building",
        "YouTube channel strategy and growth",
        "social media analytics and reporting",
        "community management and moderation",
        "influencer collaboration and partnerships",
        "social media advertising and targeting",
        "hashtag strategy and trend monitoring",
        "user-generated content campaign",
        "social media crisis management",
        "platform-specific content optimization",
        "social commerce and shoppable posts"
    ],
    "Travel": [
        "travel website and booking platform",
        "hotel reservation and management system",
        "flight booking and airline integration",
        "tour package and itinerary planning",
        "travel blog and content creation",
        "tourism marketing and destination promotion",
        "travel agency management system",
        "vacation rental and property management",
        "travel insurance and customer support",
        "transportation and logistics platform",
        "travel review and recommendation engine",
        "cruise booking and management",
        "adventure tourism and activity booking",
        "corporate travel management",
        "travel loyalty program and rewards"
    ],
    "Architecture": [
        "architectural design and building planning",
        "BIM building information modeling",
        "3D visualization and architectural rendering",
        "sustainable and green building design",
        "interior space planning and layout",
        "urban planning and city design",
        "structural engineering and analysis",
        "landscape architecture and outdoor design",
        "historical preservation and renovation",
        "commercial building design and development",
        "residential architecture and home design",
        "architectural portfolio and presentation",
        "construction documentation and blueprints",
        "accessibility in architectural design",
        "environmental impact assessment for buildings"
    ],
    "Construction": [
        "construction project management and scheduling",
        "building site operations and safety",
        "construction cost estimation and budgeting",
        "contractor management and procurement",
        "construction quality control and inspection",
        "heavy equipment and resource management",
        "construction safety compliance and OSHA",
        "building permit and regulatory compliance",
        "construction progress tracking and reporting",
        "supply chain management for construction",
        "modular and prefab construction methods",
        "demolition planning and waste management",
        "construction technology and innovation",
        "road and infrastructure construction",
        "renovation and remodeling project management"
    ],
    "CustomerSupport": [
        "customer support chatbot and helpdesk",
        "customer service management system",
        "ticketing system and issue tracking",
        "knowledge base and FAQ management",
        "customer feedback and satisfaction survey",
        "live chat and real-time support",
        "call center management and routing",
        "customer onboarding and success",
        "support analytics and performance metrics",
        "multichannel support and omnichannel strategy",
        "customer complaint resolution process",
        "self-service portal and documentation",
        "SLA management and escalation procedures",
        "customer retention and loyalty programs",
        "community forum and peer support"
    ],
    "Sales": [
        "sales strategy and pipeline management",
        "CRM implementation and optimization",
        "lead generation and qualification",
        "sales enablement and training materials",
        "proposal writing and presentation",
        "pricing strategy and revenue optimization",
        "sales forecasting and analytics",
        "account management and relationship building",
        "cold outreach and prospecting",
        "sales automation and workflow",
        "enterprise sales and B2B strategy",
        "e-commerce sales and conversion",
        "negotiation tactics and closing techniques",
        "sales territory planning and management",
        "channel partnership and reseller program"
    ]
}

# =============================================================================
# PROMPT TYPE CORPUS — 12 prompt types, 8+ examples each
# =============================================================================
PROMPT_TYPE_CORPUS = {
    "Coding": [
        "write a Python function to process data",
        "build an API endpoint with authentication",
        "create a React component with state management",
        "implement a sorting algorithm in JavaScript",
        "develop a database migration script",
        "fix the bug in the authentication middleware",
        "refactor the legacy code to use async await",
        "build a CLI tool for file processing"
    ],
    "Business": [
        "create a business plan for a new startup",
        "develop a go-to-market strategy",
        "write a project proposal for stakeholders",
        "analyze the competitive landscape",
        "create an OKR framework for the team",
        "develop a pricing strategy for the product",
        "write a quarterly business review",
        "plan the annual budget and resource allocation"
    ],
    "Marketing": [
        "write a compelling ad copy for the campaign",
        "create a content marketing strategy",
        "develop email sequences for lead nurturing",
        "write SEO-optimized blog posts",
        "create a social media content calendar",
        "design a landing page conversion strategy",
        "develop an influencer outreach plan",
        "write a press release for the product launch"
    ],
    "AIAgent": [
        "design an AI agent with tool-calling capabilities",
        "build a multi-agent system for customer support",
        "create an autonomous coding assistant",
        "design a RAG-based knowledge retrieval agent",
        "build a workflow automation agent with n8n",
        "create a research agent that searches the web",
        "design an AI agent with memory and planning",
        "build a conversational AI with persona"
    ],
    "Image": [
        "generate a photorealistic product image",
        "create a digital artwork in watercolor style",
        "design a logo with minimalist aesthetics",
        "generate a portrait with cinematic lighting",
        "create an architectural visualization rendering",
        "generate a fantasy landscape illustration",
        "design a social media post graphic",
        "create a game character concept art"
    ],
    "Video": [
        "create a promotional video for the product",
        "generate an animated explainer video",
        "produce a social media reel with transitions",
        "create a cinematic trailer for the brand",
        "generate an educational tutorial video",
        "produce a music video with visual effects",
        "create a product demo and walkthrough",
        "generate a video advertisement"
    ],
    "Resume": [
        "write a professional resume for a software engineer",
        "create an ATS-optimized CV for job applications",
        "write a compelling cover letter",
        "optimize a LinkedIn profile for recruiters",
        "create a portfolio presentation",
        "write a professional bio for the website",
        "develop an executive summary for career transition",
        "create a curriculum vitae for academic positions"
    ],
    "Email": [
        "write a professional business email",
        "create a cold outreach email sequence",
        "draft a follow-up email after a meeting",
        "write an email newsletter for subscribers",
        "create a customer onboarding email series",
        "draft an apology email for service disruption",
        "write a partnership proposal email",
        "create an event invitation email"
    ],
    "Research": [
        "conduct a systematic literature review",
        "write a research paper abstract",
        "create a research methodology framework",
        "analyze experimental data and results",
        "write a comprehensive market research report",
        "design a survey for user research",
        "create a research proposal for funding",
        "summarize findings from multiple studies"
    ],
    "Workflow": [
        "design a CI/CD deployment workflow",
        "create an automated data processing pipeline",
        "design an approval workflow for documents",
        "build a customer onboarding workflow",
        "create a content publishing workflow",
        "design an incident response workflow",
        "build a sales qualification workflow",
        "create a project management workflow"
    ],
    "Automation": [
        "automate repetitive data entry tasks",
        "create automated testing pipeline",
        "build email automation with triggers",
        "automate server provisioning and configuration",
        "create automated backup procedures",
        "build robotic process automation for HR",
        "automate social media posting schedule",
        "create automated monitoring and alerting"
    ],
    "Documentation": [
        "write comprehensive API documentation",
        "create a user guide and manual",
        "write technical specification document",
        "create a system architecture document",
        "write a runbook for operations",
        "create developer onboarding documentation",
        "write a changelog and release notes",
        "create a knowledge base with FAQs"
    ]
}
