import os
import re

filepath = r'c:\Users\shara\OneDrive - SIDDHARTH GROUP OF INSTITUTIONS\Desktop\Prompt Bazaar\Prompt Bazaar1\Prompt Bazaar\Prompt Bazaar\PromptVerse\templates\academy.html'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Replace the rm-roadmap-wrapper section
pattern1 = re.compile(r'(<!-- Roadmap Phase \+ Accordion -->\s*)<div class="rm-roadmap-wrapper">.*?</div><!-- end rm-roadmap-wrapper -->', re.DOTALL)
replacement1 = r'\1<div class="rm-roadmap-wrapper" id="roadmap-curriculum-wrapper">\n                <!-- Dynamically generated by academy.js to prevent curriculum mismatch -->\n            </div><!-- end rm-roadmap-wrapper -->'

content = pattern1.sub(replacement1, content)

# Remove the inline script toggleRoadmapModule
pattern3 = re.compile(r'\s*window\.toggleRoadmapModule = function \(headerElement\) \{.*?\n    \}', re.DOTALL)
content = pattern3.sub('', content)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print('Updated academy.html')
